export  enum Poste{
  MAINOEUVRE="MAINOEUVRE",
  OPERATEUR="OPERATEUR",
  CHEFDEQUIPE="CHEFDEQUIPE",
  MECANISIEN="MECANISIEN",
  SOUDEUR="SOUDEUR",
  ELECTRECIEN=" ELECTRECIEN",
  CONSIERGE="CONSIERGE",
  CHAUFFEUR="CHAUFFEUR",
  INGENIEUR="INGENIEUR",
  CHEFSERVICE="CHEFSERVICE",
  CHEFDEVISION="CHEFDEVISION",
  DIRECTEUR="DIRECTEUR",
  ADMINISTRATEUR="ADMINISTRATEUR",
  POINTEAU="POINTEAU",
  TECHNECIENSUPERIEUR="TECHNECIENSUPERIEUR",
  CONTREMAITRE="CONTREMAITRE"

}
