export enum Unit {
  TONNE_PER_HOUR = 'TONNE_PER_HOUR',
  CUBIC_METER_PER_HOUR = 'CUBIC_METER_PER_HOUR',
  CELSIUS = 'CELSIUS',
  MILLIMETER_CE = 'MILLIMETER_CE',
  WATT = 'WATT',
  MILLIMETER_PER_SECOND = 'MILLIMETER_PER_SECOND'
}
